# Generated by Django 4.1.2 on 2022-10-13 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='audition',
            field=models.CharField(choices=[('no', 'Currently no'), ('small', 'I have small audition'), ('sufficient', 'I have sufficient audition')], default='no', help_text='Do you have an audience that you want to share your course with?', max_length=25),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='user',
            name='full_name',
            field=models.CharField(max_length=255, verbose_name='Full Name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_mentor',
            field=models.BooleanField(default=False, verbose_name='Are you mentor?'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='type_of_teaching',
            field=models.CharField(choices=[('private', 'personally, privately'), ('professional', 'personally, professionally'), ('online', 'online'), ('other', 'other')], default='other', help_text='What kind of teaching have you done before?', max_length=25),
        ),
    ]
